import "./globals.css"
import { Inter } from 'next/font/google'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const inter = Inter({
  style: 'normal',
  weight: ['100', '200', '400', '500', '600', '800'],
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  )
}
